# Generated by Django 3.2.25 on 2024-04-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='用户')),
                ('tel', models.CharField(max_length=128, verbose_name='手机号')),
                ('password', models.CharField(default='123456', max_length=128, verbose_name='密码')),
            ],
            options={
                'verbose_name_plural': '用户表',
            },
        ),
    ]
