# Generated by Django 3.2.25 on 2024-04-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='保密', max_length=128, verbose_name='家庭住址'),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0, verbose_name='年龄'),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='暂无', max_length=128, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.BooleanField(choices=[(1, '男'), (0, '女')], default=1, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=128, verbose_name='用户名'),
        ),
    ]
