# Generated by Django 3.2.25 on 2024-04-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(max_length=18, verbose_name='手机号'),
        ),
    ]
