# Generated by Django 3.2.25 on 2024-04-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='123456', max_length=128, verbose_name='密码的md5值'),
        ),
    ]
