# Generated by Django 3.2.25 on 2024-04-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='words',
            field=models.CharField(default='我思故我在', max_length=255, verbose_name='个性签名'),
        ),
    ]
