# Generated by Django 3.2.25 on 2024-04-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_user_words'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=128, verbose_name='题目')),
                ('a', models.CharField(max_length=128, verbose_name='A')),
                ('b', models.CharField(max_length=128, verbose_name='B')),
                ('c', models.CharField(max_length=128, verbose_name='C')),
                ('d', models.CharField(max_length=128, verbose_name='D')),
                ('correct', models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], max_length=4, verbose_name='正确答案')),
            ],
            options={
                'verbose_name': '题库',
                'verbose_name_plural': '题库',
                'ordering': ['id'],
            },
        ),
    ]
