# Generated by Django 3.2.25 on 2024-04-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_questionbank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='correct',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=4, verbose_name='正确答案'),
        ),
    ]
