# Generated by Django 3.2.25 on 2024-04-17 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_questionbank_correct'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatiResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('questionId', models.CharField(max_length=255, verbose_name='题目id')),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=4, verbose_name='答案')),
                ('correct', models.BooleanField(choices=[(1, '正确'), (0, '错误')], default=1, verbose_name='答题情况')),
                ('time', models.DateField(auto_now_add=True, verbose_name='答题时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '答题结果',
                'verbose_name_plural': '答题结果',
                'ordering': ['time'],
            },
        ),
    ]
