# Generated by Django 3.2.25 on 2024-04-17 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_datiresult'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DatiResult',
            new_name='QuestionResult',
        ),
    ]
