# Generated by Django 3.2.25 on 2024-04-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_datiresult_questionresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresult',
            name='user',
            field=models.CharField(max_length=255, verbose_name='用户'),
        ),
    ]
