# Generated by Django 3.2.25 on 2024-04-17 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_questionresult_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='用户'),
        ),
    ]
