# Generated by Django 3.2.25 on 2024-04-17 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_questionresult_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionresult',
            name='user',
        ),
    ]
