# Generated by Django 3.2.25 on 2024-04-17 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_questionresult_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionResult',
        ),
    ]
