# Generated by Django 3.2.25 on 2024-04-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_questionresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionresult',
            options={'verbose_name': '答题结果', 'verbose_name_plural': '答题结果'},
        ),
        migrations.AddField(
            model_name='questionresult',
            name='answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default=1, max_length=4, verbose_name='答案'),
        ),
        migrations.AddField(
            model_name='questionresult',
            name='correct',
            field=models.BooleanField(choices=[(1, '正确'), (0, '错误')], default=1, verbose_name='答题情况'),
        ),
        migrations.AddField(
            model_name='questionresult',
            name='questionId',
            field=models.CharField(default=-1, max_length=255, verbose_name='题目id'),
        ),
    ]
