# Generated by Django 3.2.25 on 2024-04-17 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20240417_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresult',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='用户'),
        ),
    ]
