# Generated by Django 3.2.25 on 2024-04-17 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_questionresult_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresult',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='用户'),
        ),
    ]
