# Generated by Django 3.2.25 on 2024-04-17 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_questionresult_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresult',
            name='questionId',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='app.questionbank', verbose_name='题目id'),
        ),
    ]
