# Generated by Django 3.2.25 on 2024-04-17 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_questionresult_questionid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionresult',
            options={'ordering': ['time'], 'verbose_name': '答题结果', 'verbose_name_plural': '答题结果'},
        ),
        migrations.AlterField(
            model_name='questionresult',
            name='questionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.questionbank', verbose_name='题目'),
        ),
    ]
