# Generated by Django 3.2.25 on 2024-04-18 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20240417_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionresult',
            old_name='questionId',
            new_name='question',
        ),
    ]
