# Generated by Django 3.2.25 on 2024-04-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_rename_questionid_questionresult_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresult',
            name='correct_or_not',
            field=models.BooleanField(choices=[(1, '正确'), (0, '错误')], default=1, verbose_name='答题情况'),
        ),
        migrations.AlterField(
            model_name='questionresult',
            name='answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default=1, max_length=4, verbose_name='用户回答'),
        ),
        migrations.AlterField(
            model_name='questionresult',
            name='correct',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default=1, max_length=4, verbose_name='正确答案'),
        ),
    ]
