# Generated by Django 3.2.25 on 2024-04-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20240418_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresult',
            name='question',
            field=models.CharField(max_length=128, verbose_name='题目'),
        ),
    ]
