# Generated by Django 3.2.25 on 2024-04-18 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_questionresult_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresult',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.questionbank', verbose_name='题目'),
        ),
    ]
