# Generated by Django 3.2.25 on 2024-04-30 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_questionresult_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_plate_recognition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plate_number', models.CharField(max_length=128, verbose_name='车牌号')),
                ('plate_color', models.CharField(max_length=128, verbose_name='车牌颜色')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='用户')),
            ],
        ),
    ]
