# Generated by Django 3.2.25 on 2024-04-30 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_car_plate_recognition_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car_plate_recognition',
            options={'ordering': ['id'], 'verbose_name': '车牌识别结果', 'verbose_name_plural': '车牌识别结果'},
        ),
    ]
