# Generated by Django 3.2.25 on 2024-04-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_car_plate_recognition_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_plate_recognition',
            name='plate_img',
            field=models.CharField(default='', max_length=128, verbose_name='车牌图片'),
        ),
        migrations.AlterField(
            model_name='car_plate_recognition',
            name='plate_color',
            field=models.CharField(default='', max_length=128, verbose_name='车牌颜色'),
        ),
        migrations.AlterField(
            model_name='car_plate_recognition',
            name='plate_number',
            field=models.CharField(default='', max_length=128, verbose_name='车牌号'),
        ),
    ]
