# Generated by Django 3.2.25 on 2024-04-30 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20240430_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car_plate_recognition',
            options={'ordering': ['time'], 'verbose_name': '车牌识别结果', 'verbose_name_plural': '车牌识别结果'},
        ),
        migrations.AddField(
            model_name='car_plate_recognition',
            name='time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='识别时间'),
            preserve_default=False,
        ),
    ]
