# Generated by Django 3.2.25 on 2024-04-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20240430_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresult',
            name='questionID',
            field=models.IntegerField(default=0, verbose_name='题目ID'),
        ),
    ]
