# Generated by Django 3.2.25 on 2024-05-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_questionresult_questionid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traffic_sign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sign_name', models.CharField(default='', max_length=128, verbose_name='标志名称')),
                ('sign_img', models.CharField(default='', max_length=128, verbose_name='标志图片')),
                ('sign_description', models.CharField(default='', max_length=128, verbose_name='标志描述')),
            ],
            options={
                'verbose_name': '交通标志',
                'verbose_name_plural': '交通标志',
                'ordering': ['id'],
            },
        ),
    ]
