# Generated by Django 3.2.25 on 2024-05-06 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_traffic_predict_result_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='traffic_sign_research_history',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('search_history', models.CharField(default='', max_length=128, verbose_name='查询历史')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='查询时间')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='查询用户')),
            ],
            options={
                'verbose_name': '交通标志查询历史',
                'verbose_name_plural': '交通标志查询历史',
                'ordering': ['-time'],
            },
        ),
    ]
