# Generated by Django 3.2.25 on 2024-05-06 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_traffic_sign_research_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='traffic_sign_comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sign_name', models.CharField(default='', max_length=128, verbose_name='标志名称')),
                ('comment', models.CharField(default='', max_length=128, verbose_name='评论内容')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='评论用户')),
            ],
            options={
                'verbose_name': '交通标志评论',
                'verbose_name_plural': '交通标志评论',
                'ordering': ['-time'],
            },
        ),
    ]
